/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zkwcbyxiwklihegjhuql"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprd2NieXhpd2tsaWhlZ2podXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MTUyNDIsImV4cCI6MjA4MTk5MTI0Mn0.XFif2SYWfDs-MD-HQbGJ2VC0GoCr_n5yd_HBx2MHUUY"